### ISSUE TITLE
express-validator for city

### ISSUE THREAD

**Issue by dirtyhoops** [jonathananddaryll/artemis-crm#133]
check('city', 'Please use letters or numbers only')
    .optional({ nullable: true, checkFalsy: true })
    .isAlphanumeric()
    .isLength(),

remove the isAlphanumeric() because it's not letting users to input any spaces. 

example, "Mountain View" is throwing an error. 

Probably better to make it location instead of city so a user can put like "Mountain View, CA"

**Comment by collectivenectar** [comment]
Fixed city validator in commit 1ac6ecb
