### ISSUE TITLE
express-validator for contacts

### ISSUE THREAD

**Issue by dirtyhoops** [jonathananddaryll/artemis-crm#134]
Be more specific with the Error message. Add the name of the input that throw an error. 

ex.
  check('twitter', 'Please enter a valid URL')  TO  check('twitter', 'Please enter a valid Twitter handle URL')
  check('city', 'Please use letters or numbers only') TO   check('city', 'Please use letters or numbers only for city')

**Comment by collectivenectar** [comment]
Fixed validator messages in commit 1ac6ecb
