### ISSUE TITLE
Tech Stack + Libraries

### ISSUE THREAD

**Issue by collectivenectar** [jonathananddaryll/artemis-crm#2]
Proposed Tech Stack:

Frontend

React via Vite
Redux/useContext + React Redux + Redux Toolkit
Toastify?
Clerk.dev?
Jest

Backend

Clerk.dev?
Node
Express
PostgreSQL (on Neon.tech)
AWS S3 || Backblaze
Jest

Anything to add/remove?

**Comment by dirtyhoops** [comment]
Redux/useContext for state management.

**Comment by collectivenectar** [comment]
Here is some stuff I was able to find quickly, maybe or maybe not usable but worth a shot:

Web Services / APIs

https://platform.openai.com/docs/guides/completion/introduction - low priority is free

https://developers.google.com/gmail/api/guides - complete API for gmail - allows to create, send, read/receive/inbox inside the app

Libraries

https://www.npmjs.com/package/copy-to-clipboard - select text and copy to clipboard (for the chatgpt service and other copy & paste type things)

https://www.npmjs.com/package/react-document-preview - preview files as an image (for reading email files and for double checking the correct resume/cover letter before sending)
 
https://www.npmjs.com/package/@syncfusion/ej2-react-kanban - straight kanban library

https://www.npmjs.com/package/rss - rss feeds

https://www.npmjs.com/package/sortablejs - drag and drop lists (could be useful to build our own kanban)

**Comment by collectivenectar** [comment]
https://developers.google.com/cloud-search/docs/guides/search-widget - integrate a search widget into the app for both job searching and contact research

**Comment by collectivenectar** [comment]
Main tech stack is chosen for the most part, closing this issue for now.
