### ISSUE TITLE
UI Wireframe

### ISSUE THREAD

**Issue by collectivenectar** [jonathananddaryll/artemis-crm#3]
We need a complete UI wireframe that includes the MVP features we settled on in issue #1 :

Contacts Organizer
Job Tracker
Job search
Cloud docs
Job notifications
Reminders
Customization

something that preferably leaves an opening for the stretch goal features too:

Analytics
AI writing assistant
Email automation

**Comment by dirtyhoops** [comment]
Did a basic wireframe that has some of the MVP features: contacts organizer, cloud docs, job tracker. Along with the ERD, we will be able to start the building the DFD. I'm going to build Job search and reminders wireframe in the upcoming days.
